# Computational Biology Python Tools
# Last updated: 8/15/23
#
#
# Packages included in this file:
#   - dnaToolkit.py
#
# https://www.stephendoescomp.bio
# Stephen Cheney © 2023

from bio_seq import *
from aa_seq import *
from fasta_tk import *


class main:
   dna = bio_seq("GGTTTCCATCGCATGTGCGCTCCGAGTCCCTTCCTGAGCACGTCAAGCGGGCCGTACGAGATCTATAGTTAGGTAGACAGCTGGTGCAAAGACTAACCCGGCTGGTCGTGAGGACCTTGGACGGACTGTCAAAGCCTCGTATGTCCTCACAAGCCAGATTAGTGGTCCTACCCCACATATAGGGTGCGTGACCGCTGGCTAAGCAATTTCTATGCAGGGAATGTTTCTTTCCCTTTGGTCGCGACACTACAGAGCCTCGGGACTTGACAGTAATGTTAATCAGTCAAACGCCCTGTGCTTAGGTCATACGCACATTCTTTAGACAACCTGATTGCTGACGAATTGGACACTTGGCAATTTCAGGCCGTTATCTCTATCCATATACACGGTTTTAAAAAGCTCAGGCACTCTAAAAGGTCAGGGGAACAAAGGTCTGTCGTATAGGCAACTTTCGTAGCCTCAGAGACTTCACGGGATATGCATTCACTGTAGTCACATTTTCTGGTATTCGCAGACCGGCTGGTAACTCTCAACTAGTTGTCTCGACACATAGAGCGTAAATCTGACATCTCGTCCCGAACTGCACACGTCGCTAGGTACCCAAGGCGTGTATGCGCCATAGTTCCCCTAGAGAACAGTTACATACGGATCTCGAGATCAAGAAGACTGAACAGCAACCCTTTTCGTACTTCTACTAGCAGAATCGTGGGCTCGGTCCTGGAATAACGAAAAGTTTCAGCAGTTCCACTTGGAGACAGGGGCTTTCTCTATTTGCAGAACATTGGCTTGTGCTGAACGATGCCATTAAGGGCGAGCTCCTAATGTCTTGCTACTATATTAACTATTCGGTACCCGGGCAGTTAGCTCGATTCAAAACAAAGTGATGGGACGAACGCAATCAACGTTGACACAGGTCCAAAGTGCAAAGTAGACCGTCAAGGTAGTAACAGC")
   rna = bio_seq('AUGACGUUUA','RNA')
   print(dna.transcribe().getAllORFProteins(ordered = True))

   print(dfFromFASTA('test.fasta', 'DNA'))

   s1 = bio_seq('aagctcc')
   s2 = bio_seq('ctac')
   output = s1.globalAlign(s2)
   print(output[0].seqCompare(output[1]))

   fastaSeqs = parseFASTA('test.fasta', seq_type='DNA')
   print(fastaSeqs[0].seqCompare(fastaSeqs[1]))
main()